### ISSUE TITLE
Will the future version of LiteDB will be usable in Webassembly? 

### ISSUE THREAD

**Issue by YBAZAN** [mbdavid/LiteDB-vNext#5]
Hi,

I think that everything is in the question.

I see you have a repo dedicated to WebAssembly that is a fork of the current version with some features removed.

Is it something you are considering with the current work of rewriting LiteDB?

**Comment by mbdavid** [comment]
Hi @YBAZAN,

I create WebAssembly repo as a test if it's possible run complete in async and use local storage (in browser) to store data pages. 

This new version will be async be default and complete support for dependency inject for almost everywhere. This will turn LiteDB in a very customized plataform for database engines. Also, will support external plugins by default.

To LiteDB for WebAssembly will be a possible external plugin that will be added. But to work with best results, javascript IndexedDB must be used to store/retrieve data pages.

In a few months first alpha will be released!

The year 2023 is being devoted full time to LiteDB!! 😄 🎉 🆕 💾

**Comment by YBAZAN** [comment]
Thank you for your feedback @mbdavid!

Looking forward to see it in action!!
